export const constants = {
    SEARCH_MOVIE : "SEARCH_COLORS",
    SEARCH_MOVIE_SUCCESS : "SEARCH_COLORS_SUCCESS",
    SEARCH_MOVIE_FAILED : "SEARCH_COLORS_FAILED",
    FAVROUTE_MOVIE : 'SEARCH_MOVIE',
    WATCH_LIST : 'WATCH_LIST',
    ADD_FAVROUTE_MOVIE : 'ADD_FAV_MOVIE',
    ADD_WATCH_LIST : 'ADD_WATCH_LIST',
    IS_MOVIE_SEARCHING : 'IS_MOVIE_SEARCHING'
}
